### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by FeliRad-sum** [Ineherte/go-bees#43]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by Ineherte** [comment]
![image](https://user-images.githubusercontent.com/75628978/111226689-c7229400-85e1-11eb-9452-29f7bed0ec9b.png)
https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry
