### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by FeliRad-sum** [Ineherte/go-bees#47]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by Ineherte** [comment]
![image](https://user-images.githubusercontent.com/75628978/111225454-1b2c7900-85e0-11eb-8f42-2515547b5c3c.png)
![image](https://user-images.githubusercontent.com/75628978/111225475-22538700-85e0-11eb-9475-5a7a7544a0bf.png)
![image](https://user-images.githubusercontent.com/75628978/111225497-27183b00-85e0-11eb-91ac-2f0318eaa828.png)
![image](https://user-images.githubusercontent.com/75628978/111225512-2bdcef00-85e0-11eb-82a0-925fa9a3d19d.png)
![image](https://user-images.githubusercontent.com/75628978/111225526-30090c80-85e0-11eb-8f3f-b2564865a3e6.png)
![image](https://user-images.githubusercontent.com/75628978/111225545-34cdc080-85e0-11eb-9352-71e4db5c973a.png)

**Comment by Ineherte** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
